name: Setup

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Install dependencies
      shell: bash
      run: make install